- hosts: all
  remote_user: {{cookiecutter.user}}
  vars:
    repo_path: {{cookiecutter.repo_path}}
    project_root: {{cookiecutter.project_root}}
    app_name: {{cookiecutter.app_name}}
  tasks:
    - git:
        repo: "{{repo_path}}"
        dest: "{{project_root}}"
        version: HEAD

    - name: copy .env
      copy:
        src: .env.prod
        dest: "{{ project_root }}/.env"

    - name: copy nginx conf
      copy:
        src: "{{app_name}}.conf"
        dest: "/etc/nginx/conf.d/{{app_name}}.conf"

    - become: yes
      service:
        name: nginx
        state: restarted

    - copy:
        src: "{{app_name}}.service"
        dest: "/usr/lib/systemd/system/{{app_name}}.service"

    - copy:
        src: run_gunicorn.sh
        dest: "{{project_root}}/run_gunicorn.sh"
        mode: 0755

    - become: yes
      name: daemon-reload
      shell: systemctl daemon-reload

    - name: aikatsu
      become: yes
      service:
        name: aikatsu
        state: restarted

    - name: bower install
      bower:
        path: "{{project_root}}/{{app_name}}/static/"

    - name: pipenv install
      raw: "cd {{project_root}} && pipenv install"

    - name: django migrate
      command: pipenv run ./manage.py migrate
      args:
        chdir: "{{project_root}}"

    - name: django collectstatic
      command: pipenv run ./manage.py collectstatic --no-input
      args:
        chdir: "{{project_root}}"
